"""CrewAI tool for reading the test data JSON file."""

from __future__ import annotations

from typing import Any

from crewai.tools import BaseTool

from config.settings import get_settings


class ReadTestDataTool(BaseTool):
    name: str = "read_test_data"
    description: str = (
        "Read the test data JSON generated by the test data generator and "
        "return its content. No arguments are needed."
    )

    def _run(self, *args: Any, **kwargs: Any) -> str:
        settings = get_settings()
        path = settings.test_data_path
        if not path.exists():
            raise FileNotFoundError(f"Test data file not found: {path}")
        return path.read_text(encoding="utf-8")
