"""CrewAI tool for reading the business scenarios JSON file."""

from __future__ import annotations

from typing import Any

from crewai.tools import BaseTool

from config.settings import get_settings


class ReadBusinessScenariosTool(BaseTool):
    name: str = "read_business_scenarios"
    description: str = (
        "Read the business scenarios JSON generated by the database analyst and "
        "return its content. No arguments are needed."
    )

    def _run(self, *args: Any, **kwargs: Any) -> str:
        settings = get_settings()
        path = settings.business_scenarios_path
        if not path.exists():
            raise FileNotFoundError(f"Business scenarios file not found: {path}")
        return path.read_text(encoding="utf-8")
