"""CrewAI tool for reading the scenario rules JSON file."""

from __future__ import annotations

from typing import Any

from crewai.tools import BaseTool

from config.settings import get_settings


class ReadScenarioRulesTool(BaseTool):
    name: str = "read_scenario_rules"
    description: str = (
        "Read the scenario rules JSON generated by the scenario analyst and "
        "return its content. No arguments are needed."
    )

    def _run(self, *args: Any, **kwargs: Any) -> str:
        settings = get_settings()
        path = settings.scenario_rules_path
        if not path.exists():
            raise FileNotFoundError(f"Scenario rules file not found: {path}")
        return path.read_text(encoding="utf-8")
