"""CrewAI tool for reading the test cases JSON file."""

from __future__ import annotations

from typing import Any

from crewai.tools import BaseTool

from config.settings import get_settings


class ReadTestCasesTool(BaseTool):
    name: str = "read_test_cases"
    description: str = (
        "Read the test cases JSON generated by the test case designer and "
        "return its content. No arguments are needed."
    )

    def _run(self, *args: Any, **kwargs: Any) -> str:
        settings = get_settings()
        path = settings.test_cases_path
        if not path.exists():
            raise FileNotFoundError(f"Test cases file not found: {path}")
        return path.read_text(encoding="utf-8")
